import React, { useState } from "react"
import {
  getSavedSupabaseConfig,
  saveSupabaseConfig,
  testSupabaseConnection,
} from "../../lib/supabase"
import { useProducts } from "../../context/ProductContext"
import { SupabaseConfig } from "../../types"
import {
  Cloud,
  CheckCircle,
  AlertCircle,
  Database,
  Layers,
  Zap,
  ShieldAlert,
  Copy,
  Check,
} from "lucide-react"

export default function SupabaseSettings() {
  const [config, setConfig] = useState<SupabaseConfig>(getSavedSupabaseConfig)
  const [testing, setTesting] = useState(false)
  const [testResult, setTestResult] = useState<{
    success: boolean
    message: string
    latencyMs?: number
  } | null>(null)
  const [copiedSql, setCopiedSql] = useState(false)
  const [isSyncing, setIsSyncing] = useState(false)
  const [syncStatus, setSyncStatus] = useState<string | null>(null)

  const { products, syncWithSupabase } = useProducts()

  const handleSave = () => {
    saveSupabaseConfig(config)
    setTestResult({
      success: true,
      message: "Configuration saved to local vault storage.",
    })
  }

  const handleTestConnection = async () => {
    setTesting(true)
    setTestResult(null)

    const result = await testSupabaseConnection(config)
    setTestResult(result)
    setTesting(false)

    if (result.success) {
      const updated = { ...config, isConnected: true }
      setConfig(updated)
      saveSupabaseConfig(updated)
    }
  }

  const handleCloudSync = async () => {
    setIsSyncing(true)
    setSyncStatus("Pushing product catalog to Supabase database...")
    const res = await syncWithSupabase()
    if (res.success) {
      setSyncStatus(
        `Successfully mirrored ${res.count} lehengas to Supabase DB table 'products'!`,
      )
    } else {
      setSyncStatus(
        "Failed to sync products. Ensure table 'products' exists in Supabase (run the SQL snippet below).",
      )
    }
    setIsSyncing(false)
  }

  const sqlSchema = `-- ==========================================================
-- Supabase SQL Schema for The Lehenga Vault
-- Run this in your Supabase Dashboard: SQL Editor -> New query
-- ==========================================================

-- 1. Create Public Storage Bucket for High-Res Imagery
INSERT INTO storage.buckets (id, name, public) 
VALUES ('lehenga-images', 'lehenga-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage RLS Policies (Allow public upload & view)
CREATE POLICY "Public Image Read" ON storage.objects 
  FOR SELECT USING (bucket_id = 'lehenga-images');

CREATE POLICY "Public Image Upload" ON storage.objects 
  FOR INSERT WITH CHECK (bucket_id = 'lehenga-images');

CREATE POLICY "Public Image Update" ON storage.objects 
  FOR UPDATE USING (bucket_id = 'lehenga-images');

CREATE POLICY "Public Image Delete" ON storage.objects 
  FOR DELETE USING (bucket_id = 'lehenga-images');

-- 2. Create Products Table (Catalog)
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  designer TEXT NOT NULL,
  price TEXT NOT NULL,
  rent TEXT NOT NULL,
  tag TEXT NOT NULL,
  available BOOLEAN DEFAULT true,
  img TEXT NOT NULL,
  thumbnail TEXT,
  description TEXT,
  sku TEXT,
  color TEXT,
  fabric TEXT,
  size TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Products Public Read" ON public.products FOR SELECT USING (true);
CREATE POLICY "Products Full Access" ON public.products FOR ALL USING (true);

-- 3. Create Page Views Table (Real-Time Live Visitor Telemetry)
CREATE TABLE IF NOT EXISTS public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pathname TEXT NOT NULL,
  title TEXT,
  session_id TEXT,
  referrer TEXT,
  device TEXT,
  browser TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Page Views Insert" ON public.page_views FOR INSERT WITH CHECK (true);
CREATE POLICY "Page Views Read" ON public.page_views FOR SELECT USING (true);
`

  const copySqlToClipboard = () => {
    navigator.clipboard.writeText(sqlSchema)
    setCopiedSql(true)
    setTimeout(() => setCopiedSql(false), 2500)
  }

  return (
    <div className="space-y-8 max-w-4xl">
      {/* Overview Banner */}
      <div className="bg-[#FAF6ED] border border-[#D4C4A0] p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <span className="text-[10px] tracking-[0.3em] uppercase text-[#8B6A3E] font-semibold">
              SuperAdmin Cloud Infrastructure
            </span>
            <h2 className="font-serif text-2xl md:text-3xl text-[#2D2418] font-semibold">
              Supabase Cloud DB &amp; Image Storage
            </h2>
            <p className="text-xs text-[#5C3D1E] mt-1">
              Offload high-res photos and telemetry logs completely to Supabase
              Free Tier with edge CDN caching.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span
              className={`px-3 py-1 text-xs uppercase tracking-wider font-semibold border flex items-center gap-1.5 ${
                config.isConnected
                  ? "bg-emerald-50 text-emerald-800 border-emerald-300"
                  : "bg-amber-50 text-amber-800 border-amber-300"
              }`}
            >
              <span
                className={`w-2 h-2 rounded-full ${
                  config.isConnected ? "bg-emerald-600" : "bg-amber-600"
                }`}
              />
              {config.isConnected
                ? "Supabase Connected"
                : "Awaiting Credentials"}
            </span>
          </div>
        </div>
      </div>

      {/* Latency Optimization Highlights */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-[#EDE3CC]/60 border border-[#D4C4A0] p-4">
          <div className="flex items-center gap-2 text-[#C9A84C] mb-2">
            <Zap className="w-4 h-4" />
            <h4 className="font-serif text-sm font-semibold text-[#2D2418]">
              Client WebP Compression
            </h4>
          </div>
          <p className="text-xs text-[#5C3D1E] leading-relaxed">
            Raw 10MB bridal photos are compressed on the fly down to ~250KB
            before uploading, preventing slow uploads and saving Supabase
            bandwidth.
          </p>
        </div>

        <div className="bg-[#EDE3CC]/60 border border-[#D4C4A0] p-4">
          <div className="flex items-center gap-2 text-[#8B6A3E] mb-2">
            <Layers className="w-4 h-4" />
            <h4 className="font-serif text-sm font-semibold text-[#2D2418]">
              0ms Blur-Up Placeholders
            </h4>
          </div>
          <p className="text-xs text-[#5C3D1E] leading-relaxed">
            A micro 40px data thumbnail is stored with each piece. The customer
            sees instant blur preview with zero layout shifts.
          </p>
        </div>

        <div className="bg-[#EDE3CC]/60 border border-[#D4C4A0] p-4">
          <div className="flex items-center gap-2 text-[#2D2418] mb-2">
            <Cloud className="w-4 h-4" />
            <h4 className="font-serif text-sm font-semibold text-[#2D2418]">
              1-Year Edge CDN Caching
            </h4>
          </div>
          <p className="text-xs text-[#5C3D1E] leading-relaxed">
            Uploads include{" "}
            <code className="text-[10px] bg-[#EDE3CC] px-1">
              cache-control: 31536000
            </code>{" "}
            for direct caching at edge PoPs worldwide.
          </p>
        </div>
      </div>

      {/* Connection Form */}
      <div className="bg-[#FAF6ED] border border-[#D4C4A0] p-6 sm:p-8 space-y-6 shadow-sm">
        <h3 className="font-serif text-xl text-[#2D2418] font-semibold border-b border-[#D4C4A0] pb-3">
          Supabase Project Credentials
        </h3>

        <div className="space-y-4">
          <div>
            <label className="block text-xs uppercase tracking-widest text-[#5C3D1E] font-medium mb-1.5">
              Supabase Project URL
            </label>
            <input
              type="text"
              value={config.url}
              onChange={(e) =>
                setConfig({ ...config, url: e.target.value.trim() })
              }
              placeholder="https://xyzabcdefghijklmno.supabase.co"
              className="w-full px-3.5 py-2.5 bg-[#FAF6ED] border border-[#D4C4A0] text-sm text-[#2D2418] font-mono focus:outline-none focus:border-[#C9A84C]"
            />
            <p className="text-[11px] text-[#8B6A3E] mt-1">
              Found in your Supabase Dashboard under{" "}
              <strong>Project Settings → API</strong>.
            </p>
          </div>

          <div>
            <label className="block text-xs uppercase tracking-widest text-[#5C3D1E] font-medium mb-1.5">
              Supabase Anon / Public Key
            </label>
            <input
              type="password"
              value={config.anonKey}
              onChange={(e) =>
                setConfig({ ...config, anonKey: e.target.value.trim() })
              }
              placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              className="w-full px-3.5 py-2.5 bg-[#FAF6ED] border border-[#D4C4A0] text-sm text-[#2D2418] font-mono focus:outline-none focus:border-[#C9A84C]"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs uppercase tracking-widest text-[#5C3D1E] font-medium mb-1.5">
                Storage Bucket Name
              </label>
              <input
                type="text"
                value={config.bucketName}
                onChange={(e) =>
                  setConfig({ ...config, bucketName: e.target.value.trim() })
                }
                placeholder="lehenga-images"
                className="w-full px-3.5 py-2.5 bg-[#FAF6ED] border border-[#D4C4A0] text-sm text-[#2D2418] font-mono focus:outline-none focus:border-[#C9A84C]"
              />
            </div>

            <div className="flex items-center justify-between p-3.5 bg-[#EDE3CC]/50 border border-[#D4C4A0] self-end">
              <div>
                <p className="text-xs uppercase tracking-wider text-[#2D2418] font-medium">
                  Auto Cloud Sync
                </p>
                <p className="text-[10px] text-[#8B6A3E]">
                  Sync product edits directly to Supabase DB
                </p>
              </div>
              <input
                type="checkbox"
                checked={config.autoSync}
                onChange={(e) =>
                  setConfig({ ...config, autoSync: e.target.checked })
                }
                className="w-4 h-4 text-[#C9A84C] accent-[#C9A84C]"
              />
            </div>
          </div>
        </div>

        {/* Test Result Message */}
        {testResult && (
          <div
            className={`p-4 border text-xs flex items-start gap-3 ${
              testResult.success
                ? "bg-emerald-50 border-emerald-300 text-emerald-900"
                : "bg-amber-50 border-amber-300 text-amber-900"
            }`}
          >
            {testResult.success ? (
              <CheckCircle className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
            ) : (
              <AlertCircle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
            )}
            <div>
              <p className="font-semibold">{testResult.message}</p>
              {testResult.latencyMs !== undefined && (
                <p className="text-[11px] text-[#5C3D1E] mt-0.5">
                  Round-trip API Latency:{" "}
                  <strong>{testResult.latencyMs} ms</strong>
                </p>
              )}
            </div>
          </div>
        )}

        {/* Actions */}
        <div className="flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-[#D4C4A0]">
          <button
            type="button"
            onClick={handleTestConnection}
            disabled={testing || !config.url}
            className="px-5 py-2.5 bg-[#EDE3CC] hover:bg-[#D4C4A0] text-[#2D2418] text-xs font-semibold uppercase tracking-wider transition-all border border-[#D4C4A0] flex items-center gap-2 disabled:opacity-50"
          >
            <Zap className="w-3.5 h-3.5 text-[#C9A84C]" />
            {testing ? "Testing Latency..." : "Test Connection & Latency"}
          </button>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={handleSave}
              className="px-6 py-2.5 bg-[#2D2418] hover:bg-[#5C3D1E] text-[#FAF6ED] text-xs font-semibold uppercase tracking-widest transition-all shadow-sm"
            >
              Save Credentials
            </button>
          </div>
        </div>
      </div>

      {/* Database Sync Panel */}
      <div className="bg-[#FAF6ED] border border-[#D4C4A0] p-6 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h4 className="font-serif text-lg text-[#2D2418] font-semibold flex items-center gap-2">
              <Database className="w-4 h-4 text-[#8B6A3E]" />
              Database Catalog Sync
            </h4>
            <p className="text-xs text-[#5C3D1E]">
              Current catalog has <strong>{products.length}</strong> items. Push
              them to your Supabase{" "}
              <code className="bg-[#EDE3CC] px-1 font-mono text-[11px]">
                products
              </code>{" "}
              table so other admins see the same cloud catalog.
            </p>
          </div>

          <button
            type="button"
            onClick={handleCloudSync}
            disabled={isSyncing || !config.url}
            className="px-5 py-2.5 bg-[#C9A84C] hover:bg-[#B8924A] text-[#FAF6ED] text-xs font-semibold uppercase tracking-wider transition-all disabled:opacity-50 flex items-center gap-2 self-start sm:self-auto"
          >
            <Database className="w-3.5 h-3.5" />
            {isSyncing ? "Syncing..." : "Push Catalog to Supabase"}
          </button>
        </div>

        {syncStatus && (
          <p className="text-xs text-emerald-800 bg-emerald-50 p-2.5 border border-emerald-200">
            {syncStatus}
          </p>
        )}
      </div>

      {/* Complete SQL Setup Script */}
      <div className="bg-[#FAF6ED] border border-[#D4C4A0] p-6 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-[#8B6A3E]" />
            <h4 className="font-serif text-base text-[#2D2418] font-semibold">
              Complete Supabase SQL Setup Script
            </h4>
          </div>
          <button
            onClick={copySqlToClipboard}
            className="px-3 py-1 bg-[#EDE3CC] border border-[#D4C4A0] text-xs font-medium text-[#2D2418] hover:border-[#2D2418] flex items-center gap-1.5 transition-all"
          >
            {copiedSql ? (
              <Check className="w-3.5 h-3.5 text-emerald-700" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
            {copiedSql ? "Copied!" : "Copy SQL Script"}
          </button>
        </div>
        <p className="text-xs text-[#5C3D1E]">
          Run this in your Supabase Dashboard's <strong>SQL Editor</strong> to
          configure the{" "}
          <code className="bg-[#EDE3CC] px-1">lehenga-images</code> bucket,{" "}
          <code className="bg-[#EDE3CC] px-1">products</code> table, and{" "}
          <code className="bg-[#EDE3CC] px-1">page_views</code> table:
        </p>
        <pre className="bg-[#2D2418] text-[#FAF6ED] p-4 text-[11px] font-mono overflow-x-auto border border-[#5C3D1E] max-h-64">
          {sqlSchema}
        </pre>
      </div>
    </div>
  )
}
